SPRITE_SCALING_PLAYER = 0.2
SPRITE_SCALING_enemy = 0.2
SPRITE_SCALING_LASER = 0.1

OFFSCREEN_SPACE = 50

SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
SCREEN_TITLE = "Space invaders"

LEFT_LIMIT = -OFFSCREEN_SPACE
RIGHT_LIMIT = SCREEN_WIDTH + OFFSCREEN_SPACE
BOTTOM_LIMIT = -OFFSCREEN_SPACE
TOP_LIMIT = SCREEN_HEIGHT + OFFSCREEN_SPACE

ENEMY_VERTICAL_MARGIN = 15
RIGHT_ENEMY_BORDER = SCREEN_WIDTH - ENEMY_VERTICAL_MARGIN
LEFT_ENEMY_BORDER = ENEMY_VERTICAL_MARGIN

ENEMY_MOVE_DOWN_AMOUNT = 30

BULLET_SPEED = 5
ENEMY_SPEED = 2 

MAX_PLAYER_BULLETS = 3
p = 100000000000000
GAME_OVER = 1 
GAME_PLAY = 0